name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16.20.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.20.2
      - name: Install and build
        run: |
            sudo apt-get install -y build-essential python2       
            npm install
            npm run build -- --prod --base-href="angular-6-material-todo"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/angular-six-test